### 获取8088用户
GET http://localhost:8088/?id=100

### 修改灰度比例值
GET http://localhost:8088/gray?ratio=100

### 通过8088调用超时接口
GET http://localhost:8088/find?sleepTime=1000

###  通过8081调用接口 修改超时
GET http://localhost:8081/setPorts?ports=8080,8089

### 根据id获取用户
POST http://localhost:8081/
Content-Type: application/json

{
  "service": "cn.yoube.afrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [200]
}
