server:
  port: 8081

afrpc:
  zkServer: localhost:2181
  zkRoot: afrpc

app:
  id: app1
  namespace: public
  env: dev
  metas: "{'dc':'bj', 'gray':'false', 'unit':'b001'}"

logging:
  level:
    root: error
    cn.yoube.afrpc: info